version: '3'
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=bolt://neo4j:7687
      - PUBLIC_CONTENT_BY_CONCEPT_API=http://public-content-by-concept-api:8080/content
      - CONTENT_RW_NEO4J=http://content-rw-neo4j:8080/content
    command: ["go", "test", "-v", "-race", "-tags=integration", "./..."]
    depends_on:
      - neo4j
      - content-rw-neo4j
      - opa
      - public-content-by-concept-api
  neo4j:
    image: neo4j:4.4-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

  public-content-by-concept-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: public-content-by-concept-api
    environment:
      - NEO_URL=bolt://neo4j:7687
      - OPA_URL=http://opa:8181
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - opa

  content-rw-neo4j:
    image: coco/content-rw-neo4j:v3.6.4
    environment:
      - NEO_URL=bolt://neo4j:7687
      - OPA_URL=http://opa:8181
      - OPA_SPECIAL_CONTENT_POLICY_PATH=content_rw_neo4j/special_content
    ports:
      - "8082:8080"
    depends_on:
      - neo4j
      - opa
    platform: linux/amd64

  opa:
    image: coco/cm-open-policy-agent:latest
    environment:
      GITHUB_USERNAME: "${GITHUB_USERNAME}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      OPA_VERSION: 0.62.1
    container_name: opa-container
    ports:
      - "8181:8181"
    platform: linux/amd64
