FROM golang:1

ENV PROJECT="public-content-by-concept-api"

COPY . /${PROJECT}/
WORKDIR /${PROJECT}

RUN echo "Fetching dependencies..." \
&& git clone https://github.com/vishnubob/wait-for-it.git

ENTRYPOINT ["./wait-for-it/wait-for-it.sh", "neo4j:7474", "-t", "60", "--"]
