##this is an example deployment.yaml that should be customized in order to meet the configuration for app k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.cluster.bolt.url
        - name: APP_PORT
          value: "{{ .Values.env.app.port }}"
        - name: APP_SYSTEM_CODE
          value: {{ .Values.service.systemCode }}
        - name: CACHE_DURATION
          value: {{ .Values.env.cache.duration }}
        - name: RECORD_HTTP_METRICS
          value: "{{ .Values.env.recordHTTPMetrics }}"
        - name: LOG_LEVEL
          value: "{{ .Values.env.logLevel }}"
        - name: DB_DRIVER_LOG_LEVEL
          value: "{{ .Values.env.dbDriverLogLevel }}"
        - name: PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host.with.protocol.insecure
        ports:
        - containerPort: {{ .Values.env.app.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.env.app.port }}
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: {{ .Values.env.app.port }}
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.openPolicyAgentSidecar }}
      - name: "{{ .Values.openPolicyAgentSidecar.name }}"
        image: "{{ .Values.openPolicyAgentSidecar.repository }}:{{ .Values.openPolicyAgentSidecar.tag }}"
        imagePullPolicy: {{ .Values.openPolicyAgentSidecar.pullPolicy }}
        env:
          - name: POLICY_BUCKET
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: opa.policy2.bucket
        ports:
          - name: http
            containerPort: 8181
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health?bundle=true
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
        args:
          - "run"
          - "--ignore=.*"
          - "--server"
          - "--log-level=error"
          - "--log-format=json"
          - "--set=services.bundlesS3Bucket.url=$(POLICY_BUCKET)"
          - "--set=services.bundlesS3Bucket.credentials.s3_signing.web_identity_credentials.aws_region=$(AWS_REGION)"
          - "--set=bundles.publicContentByConceptApi.service=bundlesS3Bucket"
          - "--set=bundles.publicContentByConceptApi.resource=public-content-by-concept-api.bundle.tar.gz"
          - "--set=bundles.publicContentByConceptApi.polling.min_delay_seconds=120"
          - "--set=bundles.publicContentByConceptApi.polling.max_delay_seconds=300"
      {{- end}}
